### ISSUE TITLE
technology-stack

### ISSUE THREAD

**Issue by jenriquejr** [koding4food/reactive-gram#1]
decide which tools/frameworks use for our application (reactive-gram means we know React is one of them)

-Build systems
-Frameworks
-Test frameworks
-Utilities
-Language APIs
-Template engines
-Debuggers

**Comment by kdemoya** [comment]
# Decided starting stack:
- **Build systems:** [Webpack](https://webpack.github.io/)
- **Server:** [NodeJS](https://nodejs.org/en/)
- **Frameworks:** [director](https://github.com/flatiron/director), [React](http://facebook.github.io/react/), [RefluxJS](https://github.com/reflux/refluxjs)
- **Tests:** [Mocha](https://mochajs.org/)
- **Utilities:** [lodash](https://lodash.com/)
- **Templating:** [React](http://facebook.github.io/react/)
- **Styling:** [SASS](http://sass-lang.com/)

# Coding Style
- **React:** [Airbnb React/JSX Style Guide](https://github.com/airbnb/javascript/tree/master/react)
- **JavaScript:** [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)
- **CSS:** [Airbnb CSS / Sass Styleguide](https://github.com/airbnb/css)

# Git workflow
- [**Forking Workflow**](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow)

**Comment by jenriquejr** [comment]
Excellent, can you add this to the project's `README.md` ??
if so, please open a PR in order to get this issue closed

**Comment by jsainthilaire** [comment]
Maybe we can use jasmine for tests, it is a runner and contains asertion utilities.

**Comment by kdemoya** [comment]
That'd make sense for me, considering jasmine is more autonomous. Thoughts? @jenriquejr

**Comment by jenriquejr** [comment]
what do we want from jasmine, that we don't have in mocha?

**Comment by jsainthilaire** [comment]
Well se want to use the assertions API which is pretty good, mocha lacks of this and if we want to use mocha, the we need to include another library for this, like chai for example.

**Comment by jenriquejr** [comment]
that is right we would need to include chai and make it part of our dependencies, on the other hand chai has a very rich api - also mocha is on active development a lot more than what jasmine is today. I am willing to use mocha with chai, not feeling that one is a deal-breaker.

**Comment by jsainthilaire** [comment]
@kdemoya @jenriquejr is ok for me, let's include chai.

**Comment by kdemoya** [comment]
I'm not religious with any of them, so I'm willing to include whichever makes more sense now. **Mocha + Chai**, then? @jsainthilaire @jenriquejr

**Comment by jenriquejr** [comment]
@kdemoya looks like we can merge #3 already.
lets start using the forking workflow
and suggested styleguides

**Comment by jsainthilaire** [comment]
Yes @kdemoya
