### ISSUE TITLE
Add JSDocs to initial structure

### ISSUE THREAD

**Issue by kdemoya** [koding4food/reactive-gram#11]
We will need to add JSDocs once #5 gets merged.

**Comment by jsainthilaire** [comment]
@kdemoya I will do it if that'sok with @jenriquejr

**Comment by jenriquejr** [comment]
@jsainthilaire, please proceed

**Comment by kdemoya** [comment]
@jsainthilaire Go ahead, remember to assign the ticket to yourself and add the label `in progress` when you start so we all know what's being worked on.

**Comment by jsainthilaire** [comment]
is there a ticket outside github?

**Comment by jsainthilaire** [comment]
@kdemoya @jenriquejr

**Comment by kdemoya** [comment]
@jsainthilaire in [Waffle](https://waffle.io/koding4food/reactive-gram), but we can manage everything from here and Waffle updates automatically. You should assign this issue to yourself and waffle will do the rest.

**Comment by jenriquejr** [comment]
@jsainthilaire we have a board on waffle.io - it depends on the interface you want to use.
waffle - github issues should be automatically synced.

**Comment by kdemoya** [comment]
@jsainthilaire Or use waffle directly, as @jenriquejr pointed out.

**Comment by jsainthilaire** [comment]
@kdemoya @jenriquejr let's agree on not to use jsdocs for describing ReactJS well known methods, such as ComponentDidMount, render...

**Comment by kdemoya** [comment]
@jsainthilaire I agree.
