### ISSUE TITLE
Remove Gulp

### ISSUE THREAD

**Issue by jsainthilaire** [koding4food/reactive-gram#22]
I think we could remove gulp-tasks, since we are using webpack, we can take advantage of the loaders.
Why do we need gulp?

@jenriquejr @kdemoya

**Comment by jenriquejr** [comment]
@jsainthilaire this was added thinking on having sass in the project. I'll take care of this!

**Comment by jsainthilaire** [comment]
Let's use the babel-loader from webpack, it supports React+ES6. @jenriquejr

**Comment by jenriquejr** [comment]
yes, we had it that on PR before gulp was added, we might need babel and also babel-loader both ad dependencies though.

**Comment by jsainthilaire** [comment]
babel-core is the other one.

**Comment by jenriquejr** [comment]
can this be closed?

**Comment by jenriquejr** [comment]
solved on #23

**Comment by jenriquejr** [comment]
solved on #23
